# -*- coding: utf-8 -*-
"""plot_numerical_solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amAyGaXrz4uMGMw6aZDNrkFZfSU1lp1a
"""

def adjust_learning_rate(optimizer, epoch, init_lr):
    lr = init_lr * 1/(1+math.exp((epoch-(num_epochs)/2)/(num_epochs/10))) 
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr
    return lr